#spring:
#jpa:
#database: POSTGRESQL
#database-platform: org.hibernate.spatial.dialect.postgis.PostgisDialect
#hibernate:
#ddl-auto: update
#show-sql: true
##datasource:
##platform: postgres
#driverClassName: org.postgresql.Driver
#url: jdbc:postgresql://localhost:5432/postgisdb
#username: user
#password: root
#

store: /store
add: adddetails
find: findStores



spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgisdb
    username: postgres
    password: root
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
      show-sql: true

